# espanso match file
matches:
  - trigger: ":espanso:"
    replace: "Hi there!"

  - trigger: ":date:"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m%d%y"

