matches:
  # Simple text replacement
  - trigger: ":espanso:"
    replace: "Hi there!"
  - trigger: "espansopath"
    replace: "C:\\Users\\ellio\\AppData\\Roaming\\espanso\\"
  - trigger: "espansopackages"
    replace: "C:\\Users\\ellio\\AppData\\Local\\espanso\\packages"
  - trigger: "\\\\can" #Trigger is "\\can" as the \ is an escape character in this context. Used to cancel espanso expansion of a trigger.
    replace: "$|$"


